Completed implementation of Cocktail.
NStro03/Cocktail-React pull request #1
Opened 2022-02-18 05:35 UTC by NStro03

2022-02-18 12:20 UTC, Ishaan-flyfin requested changes
minor comments

2022-02-18 12:20 UTC, Ishaan-flyfin commented on src/components/Cocktail.js
> +const Cocktail = ({ idDrink, strDrink, strAlcoholic, strDrinkThumb, strGlass }) => {
why these are named with `str` as prefix?

2022-02-18 12:20 UTC, Ishaan-flyfin commented on src/components/SearchForm.js
> +            onChange={() => setSearchText(searchRef.current.value)}
avoid using anonymous functions

2022-02-18 12:20 UTC, Ishaan-flyfin commented on src/pages/SingleCocktail.js
> +      setCurrentCocktail(cocktails['drinks'] ? cocktails['drinks'][0] : undefined);
we can use optional [chaining here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining)

2022-02-18 12:20 UTC, Ishaan-flyfin commented on src/pages/SingleCocktail.js
> +            {ingList.map((ing, index) => {
by reading `ingList` name does not tell me what exactly it contains
the naming could be better

2022-02-18 12:20 UTC, Ishaan-flyfin commented on src/pages/SingleCocktail.js
> +  const ingList = [
this should be handled within reducer/context
that is why we are using it to handle complex data
While accessing i should be getting it in a list from state

2022-02-18 13:47 UTC, NStro03 commented on src/components/Cocktail.js
> +const Cocktail = ({ idDrink, strDrink, strAlcoholic, strDrinkThumb, strGlass }) => {
These were the keys in the Response JSON, so used the same. @Ishaan-flyfin

2022-02-18 13:48 UTC, NStro03 commented on src/components/SearchForm.js
> +            onChange={() => setSearchText(searchRef.current.value)}
Here I had to send an argument, so had to use an anonymous function to do that. @Ishaan-flyfin

2022-02-18 13:48 UTC, NStro03 commented on src/pages/SingleCocktail.js
> +      setCurrentCocktail(cocktails['drinks'] ? cocktails['drinks'][0] : undefined);
Oh yes, I will change it.

2022-02-18 13:51 UTC, NStro03 commented on src/pages/SingleCocktail.js
> +            {ingList.map((ing, index) => {
Will change it to IngredientList

2022-02-19 03:45 UTC, Ishaan-flyfin commented on src/components/Cocktail.js
> +const Cocktail = ({ idDrink, strDrink, strAlcoholic, strDrinkThumb, strGlass }) => {
okay but here also the context comes into play to make keys readable

2022-02-19 03:46 UTC, Ishaan-flyfin commented on src/components/SearchForm.js
> +            onChange={() => setSearchText(searchRef.current.value)}
in this case need to create a new named function

2022-02-20 06:55 UTC, merged